SELECT ANIMAL_ID, NAME
FROM(
    SELECT INS.ANIMAL_ID, INS.NAME, OUTS.DATETIME - INS.DATETIME AS PERIOD
    FROM ANIMAL_INS AS INS
    RIGHT OUTER JOIN ANIMAL_OUTS AS OUTS
    ON INS.ANIMAL_ID = OUTS.ANIMAL_ID
    ) AS A
ORDER BY PERIOD DESC
LIMIT 2
